### ISSUE TITLE
Issue installing the package

### ISSUE THREAD

**Issue by EliasMasche** [pablothedolphin/Scriptable-Framework#24]
I am trying to download & install the Scriptable-Framework but doesn't appear in the packager manager, i added the code to the manifest.json file in my 2 projects from Unity 2019.3.3f1 / 2018.4.17f1 and still not luck.

I was able to add in Unity 2018.4.12f1 updated my project to 2018.4.17f1 replaced my manifest.jsjon and now that i tried to reinstall, isn't appearing again.

Idk if i am missing something, some newbie error or unity is messing up something
 
This how it looks my manifest.json file
 
![Screenshot (73)](https://user-images.githubusercontent.com/6045426/75492687-12e2ab00-5997-11ea-92d3-9d86820aad8d.png)

So if my pc/unity problem what is the best way to manual install Scriptable-Framework?. The main folder goes in PackagesCache or Assets folder of project?.

**Comment by pablothedolphin** [comment]
Hi Elias,

So this is a known issue with Unity's package manager and scoped registries which they haven't fixed yet. It comes down to how the UPM initialises itself. Fixes range from restarting your PC to creating a new Unity project. 

Your manifest looks correct to me so this is definitely a Unity issue.

Your options are to:

- Try making unity fix itself like I described above
- Keep the scoped registry and add this line to your dependencies to manually force the package to install:
`"com.open.scriptable-framework": "1.2.12"`
- Clone / download a zip of the master branch and in the package manager UI, click the + icon to add it as a local package and select the package.json file under "Scriptable Framework/Assets/Scriptable Framework" (if you're using source control and collaborating with others, don't use this option as unity will make a hard reference to the path found on your computer)
- Clone / download a zip of the master branch and copy the whole "Scriptable Framework/Assets/Scriptable Framework" folder into your project's packages folder (where your manifest is)
- Copy that same folder directly into your assets folder

Let me know how that goes and thanks for using Scriptable Framework. If you have any further problems or feature requests just let me know! I'll be accepting pull requests as well if you decide any of your own additions would be good for it.

**Comment by EliasMasche** [comment]
Hi pablo

Thanks for the details
* Didn't work even checked Windows Firewall/AV making exceptions for Unity Editor and upm-win process checking is someone is blocking him, so maybe unity problem at their side. 
* THIS worked, was able to detect, download and install, so ready to use.
![Screenshot (78)](https://user-images.githubusercontent.com/6045426/75599654-bf9b5600-5a85-11ea-9ded-17b60cf92057.png)

* worked too, thanks for the extra details about hard refs/path, because i am using git as source control
* Didn't tried this method because was already satisfied with first two methods.
* Neither tested

Thanks again, just discovered ScriptableObjects and by luck founded your repo framework for Scriptable, so know will be able to use/learn about Scriptable using the project, yeah when something appears again will let know with a close future for PR too.

**Comment by pablothedolphin** [comment]
@EliasMasche Scriptable framework is now available via open upm of you prefer that to the scoped registry approach!

**Comment by EliasMasche** [comment]
Thanks for the detail. just tested in Unity 2019.3.11f1 / 2018.4.22f1 in my personal project and a blank projects in both versions and working out of box now.
